name: gym-local

services:
  gym-auth-database:
    container_name: gym-auth-database
    build:
      context: .
      dockerfile: docker/database/Dockerfile
    environment:
      - POSTGRES_DB=gym_auth_database
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports:
      - "5531:5432"
    volumes:
      - gym_local_auth_database_volumes:/var/lib/postgresql
    networks:
      - gym-local-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d gym_auth_database" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

networks:
  gym-local-network:
    external: true

volumes:
  gym_local_auth_database_volumes:
