name: gym

services:
  gym-auth-database:
    container_name: gym-auth-database
    build:
      context: .
      dockerfile: docker/database/Dockerfile
    environment:
      - POSTGRES_DB=gym_auth_database
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports:
      - "5431:5432"
    volumes:
      - gym_auth_database_volumes:/var/lib/postgresql
    networks:
      - gym-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d gym_auth_database" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

  gym-auth-server:
    container_name: gym-auth-server
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    ports:
      - "8083:8083"
    networks:
      - gym-network
    depends_on:
      gym-auth-database:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8083/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

networks:
  gym-network:
    external: true

volumes:
  gym_auth_database_volumes:
