spring:
  application:
    name: gym-auth-server

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: false
        default_schema: gym_auth_schema

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/main-changelog.yaml
    default-schema: gym_auth_schema
    contexts: default,seed

application:
  auth:
    secret: ${APPLICATION_AUTH_SECRET}
    max-login-attempts: 3
    block-duration: PT15M
    jwt-expiration: 86400
    prefix: "Bearer"
  internal:
    secret: ${APPLICATION_INTERNAL_SECRET}
    header-name: "X-Internal-Secret"
    principal: "INTERNAL_SERVICE"
  request-uid:
    header-name: "X-Request-Uid"
    mdc-key: "requestUid"
  security:
    endpoints:
      public-endpoints:
        - "/actuator/health"
        - "/actuator/info"
      internal-pattern: "/internal/**"
      internal-prefix: "/internal/"

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

server:
  port: 8083
